( RANDOM-NUMBER GENERATOR TAKEN FROM JUPITER ACE )
( MANUAL, SEE P. 82--83 )

0 VARIABLE SEED

: SEEDON ( -- NEXT_SEED )
    SEED @ 75 U*
    75 0 D+
    OVER OVER U<
    - -
    1-
    DUP
    SEED !
;

: RND ( LIMIT -- VALUE )
    SEEDON
    U*
    SWAP DROP
;

( THIS IS A MODIFIED VERSION OF RAND, REMOVING )
( A LIKELY BUG IN PRINTED ORIGINAL )
: RAND ( SEED -- )
    ?DUP 0= IF
	15403 @ ( READ LOW TWO BYTES OF FRAMES )
    THEN
    SEED !
;
