( ZX PRINTER UTILITIES )
DECIMAL
: EMPTY_PAD PAD 0 OVER C! 1 +
  32 0 DO 32 OVER I + C! LOOP
  DROP ;
: PAD+ C>N PAD DUP C@ DUP 1 +
  PAD C! + 1 + C! ;
: STRTOPAD DUP 0 DO PAD+ LOOP
  DROP ;
: LLIST EMPTY_PAD " SCREEN: "
  STRTOPAD PAGE # 3 W> STRTOPAD
  .P 9216 16 0 DO 32 PAD C! 32 0
  DO DUP C@ 127 AND PAD I + 1 +
  C! 1 + LOOP .P LOOP DROP ;
: LPRINT EMPTY_PAD STRTOPAD .P ;

( SERIAL UTILITIES )
: SLIST 9216 16 0 DO 32 0 DO
  DUP C@ 127 AND TX DROP 1 +
  LOOP 13 TX 12 TX DROP DROP
  LOOP DROP ;




