( SERIAL UTILITIES )
  DECIMAL
    : SLIST 9216 16 0 DO
        30 0 DO
            DUP C@ 127 AND TX
              DROP 1 +
              LOOP
                13 TX 12 TX
                  DROP DROP
                    LOOP
                      DROP
                      ;




HEX 27 INTEGER DISP_7BIT
DISP_7BIT 2 * INTEGER DISP_ADDR 2 INTEGER DISP_LINES
10 INTEGER DISP_CHARS
01 INTEGER LCD_CLS_CMD
02 INTEGER LCD_HOME_CMD
04 INTEGER LCD_ENTRY_MODE
00 INTEGER LCD_NO_SHIFT
01 INTEGER LCD_WITH_SHIFT
00 INTEGER LCD_ENTRY_C_DEC
02 INTEGER LCD_ENTRY_C_INC
08 INTEGER LCD_DISP_MODE
00 INTEGER LCD_BLINK_OFF
01 INTEGER LCD_BLINK_ON
00 INTEGER LCD_CURS_OFF

01 INTEGER LCD_MASK_RS
02 INTEGER LCD_MASK_RW
04 INTEGER LCD_MASK_E
00 INTEGER LCD_NO_BACKLIGHT
08 INTEGER LCD_BACKLIGHT
00 INTEGER LCD_DATA_MODE
01 INTEGER LCD_CMD_MODE
80 INTEGER LCD_BUSY
0 VARIABLE LCD_BL_STATE

: LCD_SEND_4
_BITS ( VALUE -- )    LCD_BL_S
TATE @ OR DUP           LCD_MA
SK_E OR I2C_WRITE DROP    I2C_
WRITE DROP                ;


: LCD_SEND_NIBBLE ( VALUE -- )
    F0 AND LCD_SEND_4_BITS ;
    : LCD_SEND ( VALUE MODE --
 )      OVER F0 AND OVER LCD_D
ATA_MODE  = IF LCD_MASK_RS OR
THEN        LCD_SEND_4_BITS SW
AP 0F AND 10  * SWAP LCD_DATA_
MODE = IF       LCD_MASK_RS OR
 THEN             LCD_SEND_4_B
ITS ;             : PAUSE50 TI
ME C@ BEGIN TIME C@   OVER - U
NTIL DROP ;           : PAUSE
( N -- ) 0 DO PAUSE50     LOOP
 ;


: LCD_INIT DISP_ADDR I2C_OPEN
   DROP 30 LCD_SEND_NIBBLE 1
     I2C_DELAY 30 LCD_SEND_NIB
BLE    1 I2C_DELAY 30 LCD_SEND
_NIBBLE  1 I2C_DELAY 20 LCD_SE
ND_NIBBLE  1 I2C_DELAY LCD_BAC
KLIGHT       LCD_BL_STATE ! LC
D_FUNCTION_SET LCD_2LINE OR LC
D_FONT_507 OR    LCD_CMD_MODE
LCD_SEND           LCD_DISP_MO
DE LCD_BLINK_ON OR   LCD_CURS_
ON OR LCD_DISP_ON OR   LCD_CMD
_MODE LCD_SEND           LCD_E
NTRY_MODE LCD_NO_SHIFT OR  LCD
_ENTRY_C_INC OR              L
CD_CMD_MODE LCD_SEND I2C_CLOSE
: LCD_BL_OFF DISP_ADDR I2C_OPE
N   DROP LCD_NO_BACKLIGHT DUP
      LCD_BL_STATE ! I2C_WRITE
        I2C_CLOSE ;
        : LCD_BL_ON DISP_ADDR
I2C_OPEN    DROP LCD_BACKLIGHT
 DUP          LCD_BL_STATE ! I
2C_WRITE        I2C_CLOSE ;
                : LCD_SET_CURS
OR DISP_ADDR        I2C_OPEN D
ROP 40 * + LCD_DDRAM  OR LCD_C
MD_MODE LCD_SEND        I2C_CL
OSE ;



: LCD_SHIFT ( DIR -- )
    DISP_ADDR I2C_OPEN DROP
      LCD_DISP_SHIFT SWAP IF
        LCD_DISP_SHIFT_LEFT OR
 ELSE     LCD_DISP_SHIFT_RIGHT
 OR THEN    LCD_DISP_MOVE OR
              LCD_CMD_MODE LCD
_SEND           I2C_CLOSE ;
                : LCD_MOVE_CUR
SOR ( DIRN -- )     DISP_ADDR
I2C_OPEN DROP         LCD_DISP
_SHIFT SWAP IF          LCD_DI
SP_SHIFT_LEFT OR ELSE     LCD_
DISP_SHIFT_RIGHT OR THEN    LC
D_CURS_MOVE OR LCD_CMD_MODE
LCD_SEND I2C_CLOSE ;
: LCD_CLS ( -- ) DISP_ADDR
    I2C_OPEN DROP LCD_CLS_CMD
      LCD_CMD_MODE LCD_SEND
        I2C_CLOSE ;
        : LCD_HOME ( -- ) DISP
_ADDR       I2C_OPEN DROP LCD_
HOME          LCD_CMD_MODE LCD
_SEND           I2C_CLOSE ;
                : LCD_PRINT (
STR -- )            DISP_ADDR
I2C_OPEN DROP         DUP 0 DO
 C>N LCD_DATA_MODE      LCD_SE
ND LOOP DROP I2C_CLOSE ;




