HEX
27 INTEGER DISP_7BIT
DISP_7BIT 2 * INTEGER DISP_ADDR
2 INTEGER DISP_LINES
10 INTEGER DISP_CHARS
01 INTEGER LCD_CLS_CMD
02 INTEGER LCD_HOME_CMD
04 INTEGER LCD_ENTRY_MODE
00 INTEGER LCD_NO_SHIFT
01 INTEGER LCD_WITH_SHIFT
00 INTEGER LCD_ENTRY_C_DEC
02 INTEGER LCD_ENTRY_C_INC
08 INTEGER LCD_DISP_MODE
00 INTEGER LCD_BLINK_OFF
01 INTEGER LCD_BLINK_ON
00 INTEGER LCD_CURS_OFF

01 INTEGER LCD_MASK_RS
02 INTEGER LCD_MASK_RW
04 INTEGER LCD_MASK_E
00 INTEGER LCD_NO_BACKLIGHT
08 INTEGER LCD_BACKLIGHT
00 INTEGER LCD_DATA_MODE
01 INTEGER LCD_CMD_MODE
80 INTEGER LCD_BUSY
0 VARIABLE LCD_BL_STATE

: LCD_SEND_4_BITS ( VALUE -- )
    LCD_BL_STATE @ OR DUP
    LCD_MASK_E OR I2C_WRITE DROP
    I2C_WRITE DROP
;

: LCD_SEND_NIBBLE ( VALUE -- )
    F0 AND LCD_SEND_4_BITS
;

: LCD_SEND ( VALUE MODE -- )
    OVER F0 AND OVER LCD_DATA_MODE
    = IF
	LCD_MASK_RS OR
    THEN
    LCD_SEND_4_BITS SWAP 0F AND 10
    * SWAP LCD_DATA_MODE = IF
	LCD_MASK_RS OR
    THEN
    LCD_SEND_4_BITS
;

: PAUSE50
    TIME C@
    BEGIN
	TIME C@
	OVER -
    UNTIL
    DROP
;

: PAUSE ( N -- )
    0 DO
	PAUSE50
    LOOP
 ;

 : LCD_INIT
     DISP_ADDR I2C_OPEN DROP
     30 LCD_SEND_NIBBLE 1 I2C_DELAY
     30 LCD_SEND_NIBBLE 1 I2C_DELAY
     30 LCD_SEND_NIBBLE 1 I2C_DELAY
     20 LCD_SEND_NIBBLE 1 I2C_DELAY
     LCD_BACKLIGHT LCD_BL_STATE !
     LCD_FUNCTION_SET LCD_2LINE OR
     LCD_FONT_507 OR
     LCD_CMD_MODE LCD_SEND
     LCD_DISP_MODE LCD_BLINK_ON OR
     LCD_CURS_ON OR
     LCD_DISP_ON OR
     LCD_CMD_MODE LCD_SEND
     LCD_ENTRY_MODE LCD_NO_SHIFT OR
     LCD_ENTRY_C_INC OR
     LCD_CMD_MODE LCD_SEND
     I2C_CLOSE
 ;
 
 : LCD_BL_OFF DISP_ADDR I2C_OPEN
     DROP LCD_NO_BACKLIGHT DUP
     LCD_BL_STATE ! I2C_WRITE
     I2C_CLOSE
 ;

: LCD_BL_ON DISP_ADDR
     I2C_OPEN DROP
     LCD_BACKLIGHT DUP
     LCD_BL_STATE !
     I2C_WRITE
     I2C_CLOSE
;

 : LCD_SET_CURS
     OR DISP_ADDR
     I2C_OPEN DROP
     40 * + LCD_DDRAM OR
     LCD_CMD_MODE
     LCD_SEND
     I2C_CLOSE
;

: LCD_SHIFT ( DIR -- )
    DISP_ADDR I2C_OPEN DROP
    LCD_DISP_SHIFT
    SWAP IF
	LCD_DISP_SHIFT_LEFT OR
    ELSE
	LCD_DISP_SHIFT_RIGHT OR
    THEN

    LCD_DISP_MOVE OR
    LCD_CMD_MODE LCD_SEND
    I2C_CLOSE
;

: LCD_MOVE_CURSOR ( DIRN -- )
    DISP_ADDR I2C_OPEN DROP
    LCD_DISP_SHIFT SWAP IF
	LCD_DISP_SHIFT_LEFT OR
    ELSE
	LCD_DISP_SHIFT_RIGHT OR
    THEN
    LCD_CURS_MOVE OR
    LCD_CMD_MODE LCD_SEND
    I2C_CLOSE
;

: LCD_CLS ( -- )
    DISP_ADDR I2C_OPEN DROP
    LCD_CLS_CMD LCD_CMD_MODE LCD_SEND
    I2C_CLOSE
;

: LCD_HOME ( -- )
    DISP_ADDR I2C_OPEN DROP
    LCD_HOME LCD_CMD_MODE LCD_SEND
    I2C_CLOSE
;

: LCD_PRINT ( STR -- )
    DISP_ADDR I2C_OPEN DROP
    DUP 0 DO
	C>N LCD_DATA_MODE
	LCD_SEND
    LOOP
    DROP
    I2C_CLOSE
;
