( INP AND OUTP ARE ONLY FOR TREE FORTH )
( RST 10H; LD B,H; LD C,L; IN A,<C>; LD L,A; LD H,00; RST 08H; RET )
: INP CODE D7 44 4D ED 78 6F 26 00 CF C9 C; ; 

( RST 10H; LD B,H; LD C, L; RST 10H; OUT <C>,L; RET )
: OUTP CODE D7 44 4D D7 ED 69 C9 C; ;

DECIMAL 16 BASE C!

20 CONSTANT I2C_PORT
81 CONSTANT I2C_QUIES
0 VARIABLE I2C_BANK

01 CONSTANT SCLBIT
80 CONSTANT SDABIT

: I2C_RDPORT ( -- N )
    I2C_PORT IN
;

: I2C_WRPORT ( N -- )
    DUP I2C_PORT OUT
    I2C_BANK !
;

: I2C_SDA_LO ( -- )
    ( DATA LINE LOW )
    I2C_BANK @
    FF SDABIT - AND ( RESET BIT 7 )
    I2C_WRPORT
;

: I2C_SDA_HI ( -- )
    ( DATA LINE LOW )
    I2C_BANK @
    SDABIT OR ( SET BIT 7 )
    I2C_WRPORT
;

: I2C_SCL_LO ( -- )
    ( CLOCK LINE LOW )
    I2C_BANK @
    FF SCLBIT - AND ( RESET BIT 0 )
    I2C_WRPORT
;

: I2C_SCL_HI
    ( CLOCK LINE HIGH )
    I2C_BANK @
    SCLBIT OR ( SET BIT 0 )
    I2C_WRPORT
;
        

: I2C_MTEST ( -- FLAG )
    ( TEST IF I2C MASTER IS PRESENT )
    I2C_SDA_LO
    I2C_RDPORT
    SDABIT XOR ( IF SDA LOW, THEN SETS CORRESPONDING BIT TO 1 )

    I2C_SDA_HI
    I2C_RDPORT
    SDABIT AND ( SDA BIT SHOULD BE HIGH )

    AND SDABIT =
;

: I2C_INIT ( -- )
    ( INITIALISE DEVICE )
    I2C_QUIES
    I2C_WRPORT
;

: RL ( N -- CF N*2 )
    ( 8-BIT ROTATE LEFT )
    2 * 100 /MOD 
;


: I2C_START ( -- )
    ( ALERT PERIPHERS TO LISTEN )
    ( FOR COMMS FROM CONTROLLER )
    I2C_INIT
    I2C_SDA_LO
    I2C_SCL_LO
;

: I2C_STOP ( -- )
    ( SIGNAL END OF COMMS FROM CONTROLLER )
    I2C_SDA_LO
    I2C_SCL_LO
    I2C_SCL_HI
    I2C_SDA_HI
;

: I2C_WAIT ( -- )
    ( WAIT, ACCOMMODATING )
    ( CLOCK STRETCHING )
    BEGIN ( CHECK SDA IS HIGH )
	I2C_RDPORT
	SDABIT AND
    UNTIL
;

: I2C_READ ( FL -- N )
    ( READ DATA, ASSUMING START SEQUENCE, )
    ( I2C DEVICE, AND REGISTER ID ALREADY )
    ( TRANSFERRED )
    0 ( PLACEHOLDER FOR DATA TO READ )
    8 0 DO ( READ EIGHT BITS )
	2 * ( LEFT BIT-SHIFT PREVIOUS DATA )
	I2C_SDA_HI ( SIGNAL READY )
	I2C_SCL_HI
	I2C_WAIT ( CHECK FOR CLOCK STRETCH )
	I2C_RDPORT SDABIT AND IF ( ADD NEXT BIT )
	    1+
	THEN
	I2C_SCL_LO
    LOOP

    ( CHECK IF ACKNOWLEDGEMENT )
    SWAP IF I2C_SDA_LO THEN

    ( WRAP UP )
    I2C_SCL_HI
    I2C_SCL_LO	
;
	
: I2C_WRITE ( N -- FLAG )
    8 0 DO ( WILL WRITE 8 BITS OF DATA, MSB FIRST )
	RL ( RETRIEVE NEXT BIT, EFFECTIVELY ROTATE AND ISOLATE 9TH BIT )
	IF I2C_SDA_HI ELSE I2C_SDA_LO THEN
	I2C_SCL_HI ( SIGNAL DATA READY TO READ)
	I2C_SCL_LO
    LOOP

    DROP ( DROP DATA, AS TRANSMITTED )

    ( READ ACK TO CHECK RECEIVED )
    I2C_SDA_HI
    I2C_SCL_HI
    I2C_RDPORT
    I2C_SCL_LO
    SDABIT AND ( 0 INDICATES SUCCESS )

    IF ( FAILED )
	I2C_SDA_LO
	I2C_SCL_HI
	I2C_SDA_HI
	-1
    ELSE ( SUCCEEDED )
	0
    THEN
;    
    
: I2C_OPEN ( ADDR -- )
    I2C_START I2C_WRITE
;

: I2C_CLOSE ( -- )
    I2C_STOP
;

48 CONSTANT LM75A_7BIT
LM75A_7BIT 2 * CONSTANT LM75A_ADDR

: LM_SETUP ( -- )
    LM75A_ADDR
    I2C_OPEN

    DUP 0= IF 
	1 I2C_WRITE DROP
	0 I2C_WRITE DROP
	I2C_STOP
    THEN
;

: LM_READ ( -- T_LO T_HI FL )
    LM75A_ADDR I2C_OPEN

    DUP 0= IF ( OPEN SUCCEEDED )
	0 I2C_WRITE ( SET REG ZERO FOR READING )
	DROP ( ASSUME WORKED )
	LM75A_ADDR 1+ ( SET READ ADDRESS )
	I2C_OPEN ( RE-START )
	DROP ( ASSUME WORKED )

	( READ 9-BITS OF DATA IN TWO STEPS )
	0 I2C_READ ( MOST SIG 8 BITS )
	
	I2C_STOP
    ELSE
	0 0 ( DUMMY RESPONSE, SO STACK BALANCES )
    THEN
;


: 8TO16 ( N -- N )
    ( CORRECT 8-BIT 2'S COMPLEMENT NUMBER TO 16-BIT 2'S COMPLEMENT )
    FF AND ( ISOLATE LOW BYTE )
    80 XOR ( TOGGLE SIGN )
    80 - ( RESTORE SIGN )
;

: GETTEMP ( -- )
    LM_SETUP
    LM_READ
    SWAP 0= IF
	CR ." Temperature is " 8TO16 . ." deg C." CR
    ELSE DROP
    THEN
;

    
