DECIMAL 16 BASE C!

20 CONSTANT I2C_PORT
81 CONSTANT I2C_QUIES
0 VARIABLE I2C_BANK

01 CONSTANT SCLBIT
80 CONSTANT SDABIT

: SLA ( N - CF 2N )
    ( 8-BIT ARITHMETIC SHIFT LEFT )
    ( EQUIV. OF Z80 SLA INST )
    2 * 100 /MOD 
;

: I2C_RDPORT ( -- N )
    ( READ I2C INTERFACE STATUS )
    I2C_PORT IN
;

: I2C_WRPORT ( N -- )
    ( WRITE TO I2C INTERFACE )
    DUP
    I2C_PORT OUT
    I2C_BANK ! ( STORE COPY OF VALUE IN MEMORY )
;

: I2C_SCL_LO ( -- )
    ( SET SCL LOW )
    I2C_BANK @
    FE AND
    I2C_WRPORT
;

: I2C_SCL_HI ( -- )
    ( SET SCL HIGH )
    I2C_BANK @
    01 OR
    I2C_WRPORT
;

: I2C_SDA_LO ( -- )
    ( SET SDA LOW )
    I2C_BANK @
    7F AND
    I2C_WRPORT
;

: I2C_SDA_HI ( -- )
    ( SET SDA HIGH )
    I2C_BANK @
    80 OR
    I2C_WRPORT
;

: I2C_DELAY ( N -- )
    ( IMPLEMENT DELAY OF APPROX 10*N MICROSEC )
    0 DO LOOP
;

: I2C_INIT ( -- )
    ( INITIALISE I2C INTERFACE )
    I2C_QUIES I2C_WRPORT
;

: I2C_START ( -- )
    ( SEND I2C START SEQUENCE )
    I2C_SDA_HI
    I2C_SCL_HI
    I2C_SDA_LO
    I2C_SCL_LO
;

: I2C_STOP ( -- )
    ( SEND I2C STOP SEQUENCE )
    I2C_SDA_LO
    I2C_SCL_HI
    I2C_SDA_HI
;

: I2C_WAIT ( -- )
    ( WAIT FOR SCL HIGH )
    BEGIN
	I2C_RDPORT
	SCLBIT AND
    UNTIL
;

: I2C_READ ( ?ACK -- N )
    0 ( INIT SPACE FOR VALUE READ )
    8 0 DO ( READ EIGHT BITS )
	2 * ( SHIFT IN-PROGRESS VALUE LEFT ONE BIT )
	I2C_SDA_HI
	I2C_SCL_HI
	I2C_WAIT
	I2C_RDPORT ( READ BIT )
	SDABIT AND IF ( UPDATE VALUE )
	    1+
	THEN
	I2C_SCL_LO
    LOOP ( FOR NEXT BIT )

    SWAP IF I2C_SDA_LO ELSE I2C_SDA_HI THEN

    I2C_SCL_HI
    I2C_SCL_LO	
    I2C_SDA_HI
;

: I2C_WRITE ( N -- ) 
    8 0 DO ( WRITE 8 BITS )
	SLA ( EXTRACT NEXT BIT  AND WRITE )
	IF I2C_SDA_HI ELSE I2C_SDA_LO THEN
	I2C_SCL_HI ( PULSE CLOCK )
	1 I2C_DELAY
	I2C_SCL_LO
    LOOP ( FOR NEXT BIT )

    DROP ( DISCARD REMNANCE OF WRITE VALUE )

    ( CHECK ACKNOWLEDGEMENT )
    I2C_SDA_HI
    I2C_SCL_HI
    1 I2C_DELAY
    I2C_RDPORT
    I2C_SCL_LO
    SDABIT AND
    0= 1-
;

: I2C_OPEN ( DEVICE -- FL )
    ( TRY TO OPEN COMMS WITH DEVICE )
    I2C_START
    I2C_WRITE
;

: I2C_CLOSE ( -- )
    ( FREE I2C BUS )
    I2C_STOP
;

: ?SC137_CHK ( -- FL )
    ( CHECK IF SC137 INTERFACE IS PRESENT )
    I2C_SDA_LO
    I2C_RDPORT
    SDABIT XOR

    I2C_SDA_HI
    I2C_RDPORT
    SDABIT AND

    AND SDABIT = 1-
;


48 CONSTANT LM75A_7BIT
LM75A_7BIT 2 * CONSTANT LM75A_ADDR

: LM_SETUP
    I2C_INIT
    LM75A_ADDR I2C_OPEN

    DUP 0= IF 
	1 I2C_WRITE DROP
	0 I2C_WRITE DROP
	I2C_STOP
    THEN
;

: LM_READ
    LM75A_ADDR I2C_OPEN

    DUP 0= IF
	0 I2C_WRITE DROP
	LM75A_ADDR 1+ I2C_OPEN DROP
	1 I2C_READ
	1 I2C_READ
	I2C_STOP
    THEN
;   

DECIMAL

: 8TOFLOAT
    DUP 128 > SWAP
    UFLOAT
    ROT IF 256.0 F-
    THEN
;

: GETTEMP
    LM_SETUP LM_READ
    SWAP 8TOFLOAT
    ROT 128 AND IF 0.5 F+ THEN
    CR ." Temperature (deg. C) " F. CR
;
