SCREEN: 1
( I2C INTERFACE LOW-LEVEL )
HEX
20 INTEGER I2C_PORT
81 INTEGER I2C_QUIES
0 VARIABLE I2C_BANK
01 INTEGER SCLBIT
80 INTEGER SDABIT
: I2C_RDPORT I2C_PORT INP ;
: I2C_WRPORT DUP I2C_PORT OUTP
  I2C_BANK ! ;
: I2C_SCL_LO I2C_BANK @ SCLBIT
  FF XOR AND I2C_WRPORT ;
: I2C_SCL_HI I2C_BANK @ SCLBIT
  OR I2C_WRPORT ;
: I2C_SDA_LO I2C_BANK @ SDABIT
  FF XOR AND I2C_WRPORT ;  -->

SCREEN: 2
( I2C INTERFACE LOW-LEVEL 2 )
: I2C_SDA_HI I2C_BANK @ SDABIT
  OR I2C_WRPORT ;
: I2C_DELAY 0 DO LOOP ;
: I2C_INIT I2C_QUIES I2C_WRPORT
  ;
: I2C_START I2C_SDA_HI
  I2C_SCL_HI I2C_SDA_LO
  I2C_SCL_LO ;
: I2C_STOP I2C_SDA_LO I2C_SCL_HI
  I2C_SDA_HI ;
: I2C_WAIT BEGIN I2C_RDPORT
  SCLBIT AND UNTIL ;
                           -->

SCREEN: 3
( I2C INTERFACE READ )
: SLA 2 * 100 /MOD SWAP ;
: I2C_READ 0 8 0 DO 2 *
  I2C_SDA_HI I2C_SCL_HI
  I2C_WAIT I2C_RDPORT SDABIT
  AND IF 1 + THEN I2C_SCL_LO
  LOOP SWAP IF I2C_SDA_LO ELSE
  I2C_SDA_HI THEN I2C_SCL_HI
  1 I2C_DELAY I2C_SCL_LO
  I2C_SDA_HI ;
                           -->

SCREEN: 4
( I2C INTERFACE WRITE / CLOSE )
: I2C_WRITE 8 0 DO SLA IF
  I2C_SDA_HI ELSE I2C_SDA_LO
  THEN I2C_SCL_HI 1 I2C_DELAY
  I2C_SCL_LO LOOP DROP
  I2C_SDA_HI I2C_SCL_HI
  I2C_RDPORT I2C_SCL_LO
  SDABIT AND 0= 1 - ;
: I2C_OPEN I2C_START I2C_WRITE ;

: I2C_CLOSE I2C_STOP ;
: ?SC137_CHK I2C_SDA_LO
  I2C_RDPORT SDABIT XOR
  I2C_SDA_HI I2C_RDPORT
  SDABIT AND AND SDABIT = 1 - ;
                           -->

SCREEN: 5
( LM75A DEMO )
48 INTEGER LM75A_ID
LM75A_ID 2 * INTEGER LM75A_ADDR
: LM_SETUP I2C_INIT LM75A_ADDR
  I2C_OPEN DUP 0= IF 1 I2C_WRITE
  DROP 0 I2C_WRITE DROP I2C_STOP
  THEN ;
: LM_READ LM75A_ADDR I2C_OPEN
  DUP 0= IF 0 I2C_WRITE DROP
  LM75A_ADDR 1 + I2C_OPEN DROP
  1 I2C_READ 1 I2C_READ I2C_STOP
  THEN ;
: GETTEMP LM_SETUP LM_READ SWAP
  CR ." TEMPERATURE (DEG C) "
  80 IF .".5" ELSE .".0" THEN
  CR ;
                           -->

SCREEN: 6
( LM75A MULTITASKING DEMO )
DECIMAL
12 23 31 23 SCREEN STS
: DISPTEMP 1 STS .C
  ." TEMP (DEG C)" STS .W
  LM_SETUP LM_READ SWAP #
  STS .W 80 = IF .".5" STS .W
  ELSE .".0" STS .W THEN ;
( : PRTEMP " ->" STRTOPAD
  LM_SETUP LM_READ SWAP #
  STRTOPAD 128 AND IF .".5" ELSE
  ELSE .".0" THEN STRTOPAD
  ." DEG C" STRTOPAD ; )
( : LOGTEMP PRTIME PRTEMP .P ; )
TASK REPORTER DISPTEMP
EVERY 10 TS REPORTER
