	;; ZX Spectrum character-set codes (mostly ASCII)

_NULL:			equ $00
_TAB:			equ $06
_CARRIAGERETURN:	equ $0D
_SPACE:			equ $20     
_EXCLAMATION:		equ $21
_QUOTE:			equ $22
_HASH:			equ $23
_DOLLAR:		equ $24
_PERCENT:		equ $25
_AMPERSAND:		equ $26
_APOSTROPHE:		equ $27
_OPENBRACKET:		equ $28
_CLOSEBRACKET: 		equ $29
_ASTERISK:		equ $2A
_PLUS:			equ $2B
_COMMA:			equ $2C
_MINUS:			equ $2D
_FULLSTOP:		equ $2E
_SLASH:			equ $2F
_0:	 		equ $30
_1:			equ $31
_2:			equ $32
_3:			equ $33
_4:			equ $34
_5:			equ $35
_6:			equ $36
_7:			equ $37
_8:			equ $38
_9:			equ $39
_COLON:			equ $3A
_SEMICOLON:		equ $3B
_LESSTHAN:		equ $3C
_EQUALS:		equ $3D
_GREATERTHAN:		equ $3E
_QUESTION:		equ $3F
_AT:			equ $40
_A:			equ $41
_B:			equ $42
_C:			equ $43
_D:			equ $44
_E:			equ $45
_F:			equ $46
_G:			equ $47
_H:	 		equ $48
_I:			equ $49
_J:			equ $4a
_K:			equ $4b
_L:			equ $4c
_M:			equ $4d
_N:			equ $4e
_O:			equ $4f
_P:			equ $50
_Q:			equ $51
_R:			equ $52
_S:			equ $53
_T:			equ $54
_U:			equ $55
_V:			equ $56
_W:			equ $57
_X:			equ $58
_Y:			equ $59
_Z:			equ $5A

_TOPRIGHTBLACK:		equ $81
_TOPLEFTBLACK:		equ $82     
_TOPBLACK:		equ $83
_BOTTOMRIGHTBLACK:	equ $84
_RIGHTBLACK:		equ $85
_TOPLEFTBOTTOMRIGHT:	equ $86
_BOTTOMLEFTWHITE:	equ $87
_BOTTOMLEFTBLACK:	equ $88     
_BOTTOMLEFTTOPRIGHT:	equ $89
_LEFTBLACK:		equ $8A
_BOTTOMRIGHTWHITE:	equ $8B
_BOTTOMBLACK:		equ $8C
_TOPLEFTWHITE:		equ $8D
_TOPRIGHTWHITE:		equ $8E
_BLACK:			equ $8F
