4 CONSTANT COFFSET
3 CONSTANT ROFFSET
5000 CONSTANT TSCORE 
28 CONSTANT MAXLEVEL 
123 CONSTANT VERSION 
0 VARIABLE AIR
0 VARIABLE HISCORE
0 VARIABLE SCORE
0 VARIABLE LEVEL
0 VARIABLE BRACELET
0 VARIABLE AMULET
0 VARIABLE CAUGHT
0 VARIABLE RESETLEVEL
0 VARIABLE ENDGAME
0 VARIABLE KEYPRESS
0 VARIABLE USEJOYSTICK
CREATE CHARSET 297 ALLOT
CREATE KEYS 4 ALLOT
CREATE MUMMIES 16 ALLOT 
CREATE GAMELEVELS 4386 * ALLOT
CREATE MESSAGES 585 ALLOT 
DEFINER CODE
DOES>
  CALL
;
CODE HALT 118 C, 253 C, 233 C,
: SETUPUDG ( -- )  
  CHARSET
  BEGIN
    DUP 1+ SWAP C@
    DUP 13 - 
  WHILE
    8 * 11264 +
    8 0 DO
      >R
      DUP C@
      I C!
      1+ R> 1+
    LOOP
    DROP
  REPEAT
  DROP DROP
;
