2 CONSTANT CELL

: COUNT
    DUP 1+ SWAP C@
;

0 VARIABLE DENSITY
0 VARIABLE THETA
0 VARIABLE ID

: " ASCII " WORD ;

: INSERT_STRING ( ADDR LEN -- )
    0 DO
	DUP C@ C,
	1+
    LOOP
    
    DROP
;

DEFINER MATERIAL
  , ,
  DUP C@ 1+ INSERT_STRING 
DOES>
  DUP @ THETA !
  CELL + DUP @ DENSITY !
  CELL + ID !
;

: .SUBSTANCE ID @ COUNT TYPE ;

: FOOT 10 * ;

: INCH 100 12 */ 5 + 10 / + ;

: /TAN 1000 THETA @ */ ;

: PILE
    DUP DUP 10 */ 1000 */ 355 339 */ /TAN /TAN
    DENSITY @ 200 */ ." = " . ." TONS OF " .SUBSTANCE ;

" CEMENT" 131 700 MATERIAL CEMENT
" LOOSE GRAVEL" 93 649 MATERIAL LOOSE-GRAVEL
" PACKED GRAVEL" 100 700 MATERIAL PACKED-GRAVEL
" DRY SAND" 90 754 MATERIAL DRY-SAND
" WET SAND" 118 900 MATERIAL WET-SAND
" CLAY" 120 727 MATERIAL CLAY
