DECIMAL 

16 CONSTANT WIDTH
16 CONSTANT HEIGHT

0 VARIABLE SEED

: 2DUP ( M N -- M N M N )
    OVER OVER
;

: 2DROP ( M N -- )
    DROP DROP
;

: SEEDON ( -- NEXT_SEED )
    SEED @ 75 U*
    75 0 D+
    OVER OVER U<
    - -
    1-
    DUP
    SEED !
;

: RND ( LIMIT -- VALUE )
    SEEDON
    U*
    SWAP DROP
;

: RAND ( SEED -- )
    ?DUP 0= IF
	15403 @ ( READ LOW TWO BYTES OF FRAMES )
    THEN
    SEED !
;

: YESNO ( -- FL ) 
    ( RANDOM BINARY CHOICE )
    2 RND
;

16 BASE C!

: GR ( PATTERN<8> ASCII -- )
    8 * 2BFF + DUP
    8 +
    DO
	I C! -1
    +LOOP
;

: SETUP-UDG ( MAZE CELL BOUNDARIES ) 
    00 00 00 00 

    00 00 00 00 00 GR

    01 01 01 01

    01 01 01 01 01 GR

    00 00 00 00

    00 00 00 FF 02 GR

    01 01 01 01

    01 01 01 FF 03 GR
;

CREATE SET-LIST WIDTH 1+ ALLOT

: LIST-ADD ( N L -- )
    ( ADD NEW ELEMENT N TO END OF COUNTED LIST L )
    DUP C@ 1+ ( UPDATE LENGTH )
    DUP 3 PICK C! ( STORE NEW LENGTH )
    + C! ( STORE LIST ITEM )
;

: LIST-CLEAR ( L -- )
    ( EMPTY LIST L )
    0 SWAP C!
;

: LIST-SEARCH ( N L -- FL )
    ( CHECK FOR EXISTENCE OF ELEMENT N IN LIST L )
    DUP C@ OVER + 1+ ( WORK OUT END OF LIST )
    0 SWAP ROT 1+ ( S: FL N LIMIT START )
    DO
	I C@ 3 PICK = IF
	    DROP 1
	    LEAVE
	THEN
    LOOP
    SWAP DROP
;

CREATE MAZE WIDTH HEIGHT * 2 * ALLOT

1 VARIABLE NEXTSET

: MAZE@ ( ROW COL -- VAL )
    ( RETRIEVE MAZE CELL VALUE )
    SWAP
    WIDTH * +
    2 * MAZE +
    C@
;

: MAZE! ( VAL ROW COL -- )
    ( SET MAZE CELL VALUE )
    SWAP
    WIDTH * +
    2 * MAZE +
    C!
;

: SET@ ( ROW COL -- VAL )
    ( RETRIEVE SET MEMBERSHIP OF CELL )
    SWAP
    WIDTH * +
    2 * MAZE +
    1+
    C@
;

: SET! ( VAL ROW COL -- )
    ( UPDATE SET MEMBERSHIP OF CELL )
    SWAP
    WIDTH * +
    2 * MAZE +
    1+
    C!
;

: RESET-MAZE ( -- )
    ( ALL CELLS IN NULL SET, ALL BOUNDARIES IN PLACE )
    HEIGHT 0 DO
	WIDTH 0 DO
	    0003
	     ( WRITE CELL AND SET AT SAME TIME FOR SPEED )
	    I J WIDTH * + 2 * MAZE +
	    !
	LOOP
    LOOP

    1 NEXTSET !
;

: PRINT-ROW ( ROW -- )
    ( DISPLAY MAZE ROW TO SCREEN )
    1 EMIT ( LEFT BORDER )
    WIDTH 0 DO
	DUP I MAZE@
	EMIT
    LOOP
    CR
    DROP
;

: PRINT-MAZE ( -- )
    CR

    ( PRINT TOP ROW )
    SPACE WIDTH 0 DO
	2 EMIT
    LOOP
    CR

    ( PRINT MAZE BODY )
    HEIGHT 0 DO
	I PRINT-ROW
    LOOP
;

: PRSET ( ROW -- )
    ( DISP SET ASSIGNMENTS OF CELLS IN ROW )
    WIDTH 0 DO
	DUP I SET@
	.
    LOOP
    CR
    DROP
;

: ?RIGHT ( ROW COL -- FL )
    ( CHECK IF RIGHT WALL EXISTS )
    MAZE@ 1 AND
;

: CLEAR-RIGHT ( ROW COL -- )
    ( REMOVE RIGHT WALL )
    2DUP MAZE@
    FE AND
    ROT ROT MAZE!
;

: ?DOWN ( ROW COL -- FL )
    ( CHECK IF BOTTOM WALL EXISTS )
    MAZE@ 2 AND
;

: CLEAR-DOWN ( ROW COL -- )
    ( REMOVE BOTTOM WALL )
    2DUP MAZE@
    FD AND
    ROT ROT MAZE!
;

: ASSIGN-SETS ( ROW -- )
    ( SEARCH ROW FOR CELLS NOT ASSIGNED TO A SET )
    ( AND ASSIGN TO NEXT AVAILABLE SET )
    WIDTH 0 DO ( COLUMN BY COLUMN )
	DUP I SET@ 0= IF 
	    NEXTSET @ DUP ( S: R V V )
	    3 PICK I SET!
	    1+ NEXTSET !
	THEN
    LOOP

    DROP
;

: UPDATE-SETS ( NEW OLD ROW -- )
    WIDTH 0 DO
	DUP I SET@ ( S: NEW OLD ROW SET )
	3 PICK = IF
	    3 PICK OVER I SET!
	THEN
    LOOP

    DROP DROP DROP
;


: MERGE-RIGHT ( ROW COL -- )
    2DUP SET@ ( SET AT CURRENT CELL )
    ROT ROT
    2DUP 1+ SET@ ( SET AT CELL TO RIGHT )
    4 ROLL ( S: R C VR VL )

    2DUP > IF
	SWAP 4 PICK UPDATE-SETS
    ELSE
	4 PICK UPDATE-SETS
    THEN

    CLEAR-RIGHT
;
	
: MERGE-DOWN ( ROW COL -- )
    2DUP SET@ ( SET AT CURRENT CELL )
    ROT ROT
    OVER 1+ OVER SET@ ( SET AT CELL TO DOWN )
    4 ROLL ( S: R C VD VU )

    OVER 0= 3 PICK 3 PICK > OR IF
	SWAP DROP ( S: R C VU )
	3 PICK 1+ 3 PICK SET!
    ELSE
	DROP ( S: R C VR )
	3 PICK 3 PICK SET!
    THEN

    CLEAR-DOWN
;

: COUNT-SET ( ROW SET -- COUNT )
    0 SWAP ( S: ROW COUNT SET )
    WIDTH 0 DO
	3 PICK I SET@
	OVER = IF
	    SWAP 1+ SWAP
	THEN
    LOOP

    DROP SWAP DROP
;

: PROCESS-ROW ( ROW -- )
    ( WORK ALONG ROW, AND RANDOMLY MERGE ADJACENT )
    ( CELLS, EXCEPT BOTTOM ROW, WHERE ALWAYS MERGE )
    WIDTH 1- 0 DO
	DUP I SET@
	OVER I 1+ SET@
	- IF ( DIFFERENT )
	    DUP HEIGHT 1- = ( FINAL ROW )
	    YESNO OR IF
		DUP I MERGE-RIGHT
	    THEN
	THEN
    LOOP
    DROP
;

: PROCESS-DOWN ( ROW -- )
    ( WORK ALONG ROW, RANDOMLY PROPOGATING CELLS )
    ( DOWN AND NOTING WHICH SETS HAVE BEEN )
    ( EXTENDED )
    SET-LIST LIST-CLEAR
    WIDTH 0 DO ( CHECK EACH CELL IN TURN )
	YESNO IF
	    DUP I SET@ ( RETRIEVE SET )
	    DUP SET-LIST LIST-SEARCH 0= IF
		SET-LIST LIST-ADD
	    ELSE
		DROP
	    THEN

	    DUP I MERGE-DOWN
	THEN
    LOOP
    DROP
;

: CHECK-ROW ( ROW -- )
    WIDTH 0 DO
	DUP I SET@
	DUP SET-LIST LIST-SEARCH
	0= IF
	    OVER I MERGE-DOWN
	    SET-LIST LIST-ADD
	ELSE
	    DROP
	THEN
    LOOP
    DROP
;

: MAKE-MAZE
    RESET-MAZE
    ( PRINT TOP ROW )
    CR
    SPACE WIDTH 0 DO
	2 EMIT
    LOOP
    CR

    HEIGHT 0 DO
	I ASSIGN-SETS
	I PROCESS-ROW
	I HEIGHT 1- < IF
	    I PROCESS-DOWN
	    I CHECK-ROW
	THEN
	I PRINT-ROW
    LOOP
;
