( TO DO )
( FIX BRIBE FLAGS )
( CHANGE SO PRINCESS IS TAKEN AFTER KILLING WIZARD )
( STACK PROBLEM WITH MOUSE )
( AFTER SPECIAL MOVE REPRINT STATS )
( REENTER MOVE IF TOO WET )
( CHECK FOR SPECIAL TREASURE )

( SCREEN 1 - INTRODUCTION )

DECIMAL

( DEBUGGING )
: CHKSTK ( N -- )
    ( DISPLAY TOP N STACK ITEMS, EXCEPT N - NON-DESTRUCTIVE )
    0 SWAP DO
	I PICK . -1
    +LOOP
    CR ;

-->

( SCREEN 2 - BASIC FUNCTION )

( SOME BASIC WORDS TO BOOST VOCABULARY )
: 2DUP OVER OVER ;
: 1+ 1 + ;
: 1- 1 - ;
: PAUSE ( N -- )
    ( PAUSE OPERATION FOR N MILLISECONDS )
    S->D TIME D@ + BEGIN 2DUP TIME D@ D< UNTIL DROP DROP ;

( RANDOM NUMBER GENERATOR )
0 VARIABLE SEED
: SEEDON ( -- )
    SEED @ 75 U* 0 75 D+
    SWAP OVER OVER U< - -
    1 - DUP SEED ! ;

: RND ( N -- RAND )
    ( GENERATE RANDOM NUM BETWEEN 0 AND N-1 )
    SEEDON U* DROP ;

: RAND ( N -- )
    ( RESET SEED, USING CLOCK IF N=0 )
    ?DUP 0 = IF
	31836 @
    THEN SEED ! ;

-->

( SCREEN 3 - DATA STRUCTURES )

: ARRAY1 <BUILDS ALLOT DOES> + ; ( SIZE -- | IDX -- )
: ARRAY2 <BUILDS 2DUP C, C, * ALLOT
  DOES> DUP C@ ROT * + + 2 + ;  ( COL ROW -- )
: ARRAYST ( STRLEN STRCNT -- | IDX -- )
    <BUILDS SWAP 1 + SWAP 2DUP C, C, * ALLOT
  DOES> DUP 1+ C@ ROT * + 2 + ;

-->

( SCREEN 4 - GAME DATA )

8 11 ARRAYST BEAST ( BEAST NAMES )
"NOTHING" 0 BEAST W!
"WEREWOLF" 1 BEAST W!
"BUNYIP" 2 BEAST W!
"PHOENIX" 3 BEAST W!
"TROLL" 4 BEAST W!
"GOBLIN" 5 BEAST W!
"GIANT" 6 BEAST W!
"GORGON" 7 BEAST W!
"DRAGON" 8 BEAST W!
"OGRE" 9 BEAST W!
"WIZARD" 10 BEAST W!


( SCREEN 5 - GAME DATA, CONT'D )

9 9 ARRAYST DESC ( ADJECTIVES )
" FIENDIST" 0 DESC W!
" GREEN" 1 DESC W!
" FOUL" 2 DESC W!
" SLIMY" 3 DESC W!
" TOUGH" 4 DESC W!
" HORRIBLE" 5 DESC W!
" HUNGRY" 6 DESC W!
" NASTY" 7 DESC W!
" DIRTY" 8 DESC W!

( SCREEN 6 - TREASURES )

16 8 ARRAYST TREAS ( TREASURE DESCRIPTION )
" 10 SILVER SPOONS" 0 TREAS W!
" A JEWELLED SWORD" 1 TREAS W!
" A JAR OF RUBIES" 2 TREAS W!
" A TREASURE CHEST" 3 TREAS W!
" 50 SILVER PIECES" 4 TREAS W!
" 100 GOLD PIECES" 5 TREAS W!
" A BOX OF JEWELS" 6 TREAS W!
" A FAIR PRINCESS" 7 TREAS W!
8 ARRAY1 TREASV ( VALUE )
10 0 TREASV C! 30 1 TREASV C!
50 2 TREASV C! 200 3 TREASV C!
50 4 TREASV C! 100 5 TREASV C!
75 6 TREASV C! 1 7 TREASV C! 

-->


( SCREEN 7 - STATUS CODES )

0 VARIABLE STATUS
1 INTEGER PRINCESS ( PLAYER HAS FOUND PRINCESS )
2 INTEGER CHOICE ( PLAYER CAN CHOOSE NOT TO FIGHT )
4 INTEGER ESCAPED ( PLAYER HAS REACHED EDGE OF SWAMP )
8 INTEGER DIED ( PLAYER IS DEAD )

: CLRSTAT 0 STATUS ! ;
: CHKSTAT STATUS @ AND ;
: SETSTAT STATUS @ OR STATUS ! ;
: RESSTAT 15 XOR STATUS @ AND STATUS ! ;

-->


( SCREEN 8 - GAME STATE)
0 VARIABLE MSG
0 VARIABLE INVENT
( 1 INTEGER PRINCESS )
2 INTEGER RING
4 INTEGER WAND
8 INTEGER KNIFE
16 INTEGER XXX
0 VARIABLE KILLS
0 VARIABLE GEMS
0 VARIABLE BAT
0 VARIABLE STRENGTH
0 VARIABLE ZAP

( SCREEN 9 - HANDLING PLAYER INVENTORY )
: GET ( OBJECT -- )
    INVENT @ OR INVENT !
;
!
: HAS ( OBJECT -- FLAG )
    INVENT @ AND
;

: LEAVE ( OBJECT -- )
    255 XOR INVENT @ AND INVENT !
;

( INITIALISE PLAYER STATS )
: INITPL ( -- )
    0 KILLS ! ( RESET BEASTS KILLED )
    0 GEMS ! ( RESET TREASURE )
    0 BAT ! ( DISABLE BAT EFFECT )
    0 INVENT ! ( CARRYING NOTHING )
    1501 RND 500 + STRENGTH ! ( SET INIT STRENGTH )
;


( SCREEN 10 - MAP )

( 0 - CLEAR ; 1 - EXIT ; 2 - SWAMP ; 5 - PLAYER ; 4 - PRINCESS )
6 ARRAY1 MAPLUT 
32 0 MAPLUT C! 43 1 MAPLUT C!
83 2 MAPLUT C! 80 4 MAPLUT C!
88 5 MAPLUT C!
11 11 ARRAY2 MAP

: INITMAP ( -- )
    11 0 DO ( FILL IN BORDER )
	1 I 0 MAP C!
	1 I 10 MAP C!
	1 0 I MAP C!
	1 10 I MAP C!
    LOOP X
    10 1 DO ( FILL IN CENTRE )
	10 1 DO
	    J I MAP
	    10 RND 4 < IF
		2
	    ELSE
		0
	    THEN
	    SWAP C!
	LOOP
    LOOP
;

-->

( SCREEN 11 - MAP ADDITIONS )

: PLACEPR
    BEGIN
	3 RND 4 + 3 RND 4 + 2DUP MAP 5 =
    WHILE
	DROP DROP
    REPEAT
    MAP 4 SWAP C!
;

: PLACEPL ( -- COL ROW )
        10 RND 1 + 1 2DUP MAP 5 SWAP C! ( SET LOCN )
;
-->

( SCREEN 12 - SCREEN HANDLING )

0 0 11 11 SCREEN SCM ( MAP SCREEN )
12 0 31 11 SCREEN SCC ( INSTRUCTIONS )
: INITCO 13 CO 3 + C! ; ( EXPAND CONSOLE SCREEN )
: RESETCO 19 CO 3 + C! ; ( RESTORE CONSOLE SCREEN )

( CARRIAGE RETURN, LINE FEED ON CUSTOM SCREEN )
: CRLF ( SCR -- ) 13 OVER .C 10 SWAP .C ;

( POTENTIAL TO REMOVE CURSOR FROM SCRRENS )

( SCREEN 13 - MAP SCREEN )

: PRMAP
    1 SCM .C ( CURSOR HOME )
    11 0 DO
	11 0 DO
	    I J MAP C@
	    MAPLUT C@
	    SCM .C
	LOOP
	SCM CRLF
    LOOP
;

: PRCMPSS ( -- )
    12 SCC .C ( CLEAR SCREEN )
    "   N" SCC .W SCC CRLF
    "  W+E" SCC .W SCC CRLF
    "   S" SCC .W SCC CRLF
    " X=YOU" SCC .W SCC CRLF
    PRINCESS HAS 0= IF " P=PRINCESS" SCC .W THEN
    SCC CRLF
    " #=SWAMP" SCC .W SCC CRLF
    " #=EDGE" SCC .W SCC CRLF
    SCC CRLF
    "STRENGTH=" SCC .W STRENGTH @ # SCC .W SCC CRLF
    "TREASURE=" SCC .W GEMS @ # SCC .W SCC CRLF
;

-->

( SCREEN 14 - COMPASS AND STATS )

: MV ( COL ROW DCOL DROW -- NCOL NROW FLAG )
    3 PICK + SWAP 4 PICK + SWAP 
    ( ATTEMPT TO UPDATE PLAYER POSITION )
    2DUP MAP C@ DUP 1 = IF ( EXIT )
	ESCAPED SETSTAT
	DROP ROT DROP ROT DROP 1
    ELSE DUP 2 = IF ( SWAMP )
	    DROP DROP DROP 0
	ELSE DUP 4 = IF ( PRINCESS )
		PRINCESS SETSTAT
		DROP ROT DROP ROT DROP 1
	    ELSE
		DROP ROT DROP ROT DROP 1
	    THEN
	THEN
    THEN
;

: RMPL ( COL ROW -- COL ROW )
    ( REMOVE PLAYER FROM MAP )
    2DUP MAP 0 SWAP C!
;

: INPL ( COL ROW -- COL ROW )
    ( ADD PLAYER TO MAP )
    2DUP MAP 5 SWAP C!
;

: MVPL ( COL ROW DCOL DROW -- COL ROW FLAG )
    ( MOVE PLAYER AND DEAL WITH CONSEQUENCES )
    ( FLAG - 0 = SWAMP ; 1 = MOVED ; -1 = EXIT )
    MV
    ROT ROT INPLAYER ROT

    ( WAS MV 0= IF NOENTRY THEN MSG @ ?DUP IF FINDPRINCESS 0 MSG ! DROP THEN INPLAYER )
;

( SCREEN 15 - PLAYER MOVEMENT )

( COL ROW -- COL ROW )
( MOVE PLAYER IN DIFFERENT COMPASS DIRECTIONS )
: S  RMPLAYER  0  1 MVPLAYER ;
: N  RMPLAYER  0 -1 MVPLAYER ;
: E  RMPLAYER  1  0 MVPLAYER ;
: W  RMPLAYER -1  0 MVPLAYER ;
: SE RMPLAYER  1  1 MVPLAYER ;
: NE RMPLAYER  1 -1 MVPLAYER ;
: SW RMPLAYER -1  1 MVPLAYER ;
: NW RMPLAYER -1 -1 MVPLAYER ;


( SCREEN 16 - HANDLE MOVEMENT )

4 10 ARRAYST DIRCMD
" N" 0 DIRCMD W!
" NE" 1 DIRCMD W!
" E" 2 DIRCMD W!
" SE" 3 DIRCMD W!
" S" 4 DIRCMD W!
" SW" 5 DIRCMD W!
" W" 6 DIRCMD W!
" NW" 7 DIRCMD W!
" OUT" 8 DIRCMD W!
" MAP" 9 DIRCMD W!

: GETDIR
    S@
    -1 SWAP 10 0 DO
	I DIRCMD S= IF
	    SWAP DROP I SWAP LEAVE
	THEN
    LOOP
    CDROP
;	

( SCREEN 17 - HANDLE MOVEMENT CONT )

: ?MOVE ." WHICH WAY NOW? N, S, E, W," CR
    ." SE, NW, ETC. OR MAP" CR
;

: NOENTRY ." TOO WET THAT WAY, CLOT" CR ;

: FINDPRINCESS ." THE PRINCESS COMES WITH YOU" CR ;

: OUT 1 ABORT" DONE" ;

: DOMOVE ( X Y -- NX NY FLAG )
    BEGIN 
	GETDIR DUP -1 =
    WHILE
	    DROP
    REPEAT
      
    CASE N NE E SE S SW W NW OUT PRMAP ;
;

-->

( SCREEN 18 - MOVEMENT TEST )

: TESTMV ( -- )
    EOFF CLS INITCO
    INITMAP INITPL
    PLACEPL PLACEPR

    BEGIN
	?MOVE
	DOMOVE
	PRINCESS CHECKSTAT IF FINDPRINCESS THEN
	ESCAPED CHECKSTAT IF
	    ESCAPED CLRSTAT
	    ." YOU ESCAPED"
	THEN
	PRINTMAP
    AGAIN
;

( SCREEN 19 - HANDLE COMBAT )    
: DESCMON ( BEAST TREASURE -- BEAST TREASURE )
    ( GENERATE TWO, DIFFERENT RANDOM NUMBERS )
    OVER IF ( NOT A MOUSE ) 
	BEGIN 9 RND 9 RND 2DUP = 1- UNTIL
	." A " DESC  W@ CO .W 
	SP DESC W@ CO .W 
	SP OVER BEAST W@ CO .W
    ELSE
	" A SMALL GREY MOUSE " CO .W
    THEN
    
    SP ."  IS" CR ." GUARDING " 
    DUP TREAS W@ C0 .W CR

    ( CHECK FOR WAND )
    
    ." THEIR COMBAT POINTS COME TO "
    OVER 10 * # CO .W CR
;

( SCREEN 20 - HANDLE COMBAT )
: DISPSTRENGTH ( -- )
    ." YOUR COMBAT STRENGTH IS " STRENGTH @ # CO .W CR
;

: GETCOMBAT ( -- POINTS )
    BEGIN
	BEGIN
	    ." HOW MANY COMBAT POINTS? " 
	    S@ ># CR
	UNTIL
	DUP STRENGTH @ >
    WHILE
	    ." BUT YOU ONLY HAVE " 
	    STRENGTH @ # CO .W
	    ."  POINTS" CR
	    DROP
    REPEAT
;

-->

( SCREEN 21 )
( FIGHT SEQUENCE: ON ENTRY, STACK CONTAINS BEAST TYPE AND COMBAT )
( POINT SELECTED; ON EXIT, FLAG INDICATES H VALUE WHEN BEAST WAS )
( KILLED, OR ZERO IF NOT, OR -1 IF STALEMATE )
( IDENTIFIERS ARE AS IN ZX81 BASIC ORIGINAL )
: FIGHT ( X Y MONSTER TREASURE MSTRENGTH PSTRENGTH -- X Y MONSTER TREASURE MSTRENGTH FLAG )
    ( ADJUST PLAYER COMBAT POINTS FOR WEIGHT CARRIED )
    GEMS @ 3 * 100 / - 10 * ( K )

    SWAP
    
    ( FIGHT PARAMS )
    1000 RND ( I' )
    20 ( L )
    ( REORDER FOR EASE OF USE )
    ROT ( K - COMBAT, I, L, M - MSTRENGH )
    0 ( FLAG )
    0 1000 DO
	DROP ( DROP PREVIOUS FLAG VALUE ) 
	2DUP * ( K I L M L.M )
	5 PICK 1+ < ( K I L M L.M<=K )
	4 PICK I 1+ < ( K I L M L.M<=K I>I' )
	AND IF ( HAS PLAYER WON FIGHT )
	    I LEAVE
	ELSE
	    ROT ROT 1- ROT ( L = L-1 )
	    0
	THEN
    -50 +LOOP
    ROT DROP ROT DROP ROT DROP
;

( SCREEN 22 )

: DOFIGHT ( TREASURE MSTRENGTH -- TREASURE MSTRENGTH FLAG  )
( FLAG = 0 => PLAYER DEAD ; 1 = MONSTER DEAD )
    BEGIN
	GETCOMBAT ( TREASURE MSTRENGTH PSTRENGTH )
	STRENGTH @ OVER - STRENGTH ! ( DEDUCT FROM STRENGTH )

	FIGHT

	( CHECK OUTCOME )
	DUP 900 > IF
	    ." YOU SURE SMASHED THAT MONSTER" CR
	    DROP 1
	ELSE DUP 700 > IF
		." LUCKY HE WAS NOT AT ALL WELL" CR
		DROP 1
	    ELSE DUP 0 > IF
		    ." HE WONT GIVE YOU HIS TREASURE" CR
		    DROP
		    2 / ( DIVIDE MONSTER'S STRENGTH BY TWO )
		    0
		ELSE ( DEAD )
		    DROP -1
		THEN
	    THEN
	THEN
    ?DUP UNTIL

    1+ 2 / ( MAP ONTO 0,1 )

    DUP IF
	KILLS @ 1+ KILLS !
    THEN
;

-->

( SCREEN 23 - HANDLE BRIBE )      
: GETBRIBE ( -- BRIBE )
    BEGIN
	BEGIN
	    ." HOW MUCH DO YOU RECKON YOUR" CR
	    ." MISERABLE HIDE IS WORTH? " 
	    S@ CDUP CO .W
	    >#
	UNTIL
	DUP GEMS @ >
    WHILE
	    ." YOUR BANK MANAGER DOESN'T AGREE" CR
	    DROP
    REPEAT
;

: CHECKBRIBE ( TREASURE BRIBE -- TREASURE BRIBE FLAG )
    OVER TREASV C@ ( RETRIEVE VALUE OF TREASURE )
    22 RND ( TREASURE BRIBE VALUE CHANCE ) ( T K P II )
    0 ( T K P II L )
    ROT ( TREASURE BRIBE CHANCE L VALUE ) ( T K II L P )
    0
    20 0 DO  ( T K II L P FLAG )
	DROP ( PREVIOUS FLAG VALUE )
	( CHECK IF VALUE*L > 10*BRIBE ) 
	2DUP * 5 PICK 10 * 1- >= ( T K II L P T1 )
        ( CHECK IF RND <= I )
	4 PICK I 1+ < ( T K II L P T1 T2 )
	AND IF  ( FAIL )
	    1 LEAVE
	ELSE
	    SWAP 1+ SWAP ( L = L + 1 )
	    0 ( NOT FAILED YET )
	THEN
    LOOP
    
    SWAP DROP SWAP DROP SWAP DROP SWAP DROP
    1 SWAP - ( MAKE FLAG=1 CORRESPOND TO SUCCESS )
;

( SCREEN 24 -- HANDLE BRIBE)
: DOBRIBE ( TREASURE MSTRENGTH -- TREASURE MSTRENGTH FLAG  )
    SWAP ( MSTRENTH TREASURE )
    GETBRIBE ( MSTRENTH TREASURE BRIBE )
    CHECKBRIBE ( MSTRENTH TREASURE BRIBE FLAG )
     
    IF ( BRIBE ACCEPTED )
	." YOUR MEASLY BRIBE WAS ACCEPTED" CR
	GEMS @ SWAP - GEMS !
	SWAP 1
    ELSE ( BRIBE NOT ACCEPTED )
	." THE MONSTER SPURNS SUCH A" CR
	." PITIFULLY INADEQUATE SUM..." CR
	." WHICH IT TOOK AS AN INSULT" CR
	." NOW THREATENS TO TEAR OFF YOUR" CR
	." ARM..." CR
	." NOW YOU CAN ONLY FIGHT" CR
	DROP SWAP 0 DUP CHOICE !
    THEN
;

-->

( SCREEN 25 - HANDLE RUN AWAY )

( CHECK IF SUCCESSFULLY RUNS FROM BEAST )
( ON EXIT, FLAG = 1 IF ESCAPED, = 0 IF FIGHT, = -1 IF EATEN )
: CHECKRUN ( BEAST -- FLAG )
    12 RND ( BEAST II )
    DUP 11 = IF ( EATEN BY MONSTER )
	DROP DROP 0
    ELSE
	2 ( ASSUME DO NOT ESCAPE )
	10 0 DO
	    DROP ( DISCARD PREVIOUS FLAG )
	    OVER I 1+ < ( IS INDEX > MONSTER INDEX ) ( BEAST II T1 )
	    OVER I > ( AND RANDOM NUMBER IS LESS THAN INDEX )
	    AND
	    IF ( ESCAPES, SO DONE )
		1 LEAVE
	    ELSE
		2
	    THEN
	LOOP

	( TIDY UP STACK )
	SWAP DROP
	SWAP DROP
    THEN
;

( SCREEN 26 - HANDLE RUN AWAY )

( DO ROUTINES ALL RETURN A FLAG, WITH VALUES AS FOLLOWS )
( FLAG : 0 = DEAD; 1 = ESCAPE; 2 = FIGHT )
( ALSO, IF DEAD, DIED STATUS IS SET )

: DORUN ( MONSTER TREASURE MSTRENGTH -- MONSTER TREASURE MSTRENGTH FLAG )
    ( FLAG : 0 = DEAD; 1 = ESCAPE; 2 = FIGHT )
    3 PICK CHECKRUN

    DUP 0= IF
	." THE MONSTER RAN FASTER THAN YOU" CR
    ELSE DUP 2 = IF
	    ." BUT NOT FAST ENOUGH..." CR
	    ." NOW YOU CAN ONLY FIGHT" CR
	    0 CHOICE !
	ELSE
	    ." YOU SURE RUN FAST IF YOU NEED TO" CR
	THEN
    THEN
;

( SCREEN 27 -- MISC INTERACTIONS , WAS 21)
: DOZAP ( -- FLAG )
    ( FLAG : 1 - ZAPPED ; 2 - FIGHT )
    ZAP @ IF
	." MONSTERS DIE WHEN ZAPPED" CR
	ZAP @ 1- ZAP !
	1
    ELSE
	0 ( NO ACTION )
    THEN
;

: DOXXX ( -- )
    XXX HAS IF
	." THE *** RING EXPLODED...HOW SAD" CR
	-1 XXX PUT
    ELSE
	0 ( NO ACTION ) 
    THEN
;	


( SCREEN 28 - OTHER LOCATION INTERACTIONS )

: PIT ( -- )
    40 RND 40 + ( WORK OUT DAMAGE )
    DUP STRENGTH @ 
    SWAP -
    STRENGTH !

    ." CLUMSY-YOU JUST FELL INTO A PIT" CR
    ." OF NOISOME WATER" CR
    ." AND USED " # CO .W
    ." TO GET OUT " CR

    STENGTH @ 1 < IF
	." OR WOULD HAVE ..." CR
	." HAD YOU NOT DROWNED TRYING ..." CR
	0 STRENGTH !
	DIED SETSTAT
    THEN

    150 PAUSE
;

: EAGLE ;


( SCREEN 29 - OTHER LOCATION INTERACTIONS )

: THIEF ( -- )
    GEMS @ ?DUP IF ( CHECK IF PLAYER HAS TREASURE )
	2 / GEMS ! ( HALVE IT, IF SO )
	." A SNEAKY THIEF STOLE HALF YOUR" CR
	." TREASURE...CANT TRUST ANYONE" CR
    THEN
;

: BATTED ( X Y -- NX NY )
    BAT @ ?DUP IF ( CHECK IF BAT EFFECT IS ACTIVE )
	1 - BAT ! ( DECREMENT BAT COUNTER )
	( PRINT MESSAGE )
	." A GIANT BAT HAS TRANSPORTED YOU" CR
	." TO ANOTHER PLACE" CR
	MAP 0 SWAP ! ( CLEAR PLAYER )
	BEGIN 	( FIND NEW LOCATION )
	    7 RND 2 + 7 RND 2 + 2DUP MAP @ 1 -
	WHILE
		DROP DROP
	REPEAT
	2DUP MAP 5 SWAP !
    THEN
;


( SCREEN 30 -- TEST LOCATION INTERACTIONS )
: TESTFIGHT ( -- )
    EOFF CLS
    INITPL
    4 40 BEGIN
	DOFIGHT
	3 CHKSTK
	CR CR
	DROP
    AGAIN
;

: TESTBRIBE ( -- )
    EOFF CLS
    INITPL 1000 GEMS !
    4 40 BEGIN
	DOBRIBE
	3 CHKSTK
	CR DROP
    AGAIN
;

: TESTRUN ( -- )
    EOFF CLS
    30 30 2 BEGIN
	DORUN
	4 CHKSTK
	DROP
	100 PAUSE
    AGAIN
;


-->


( SCREEN 31 - DESCRIBE MONSTER )
: PICKMONSTER ( COL ROW -- COL ROW MONSTER )
 ( ALSO DEAL WITH SPECIAL CASES )
    BEGIN ( LOOP DEALS WITH SPECIAL CASES )
	15 RND ( PICK MONSTER )
	3 PICK 3 PICK MAP C@ 4 = IF ( CHECK FOR PRINCESS )
	    DROP 10 ( HAS TO BE WIZARD )
	THEN
	
	( SPECIAL CASES )
	DUP 10 > IF
	    11 -
	    CASE THIEF PIT BATTED EAGLE ENDCASE
	    0 ( REPEAT PROCEDURE )
	ELSE
	    1 ( DONE )
	THEN
    UNTIL
;

: ADDPET ( MSTRENGTH -- MSTRENGTH )
    9 RND 1+ ( WORK OUT PET )
    ." THE WIZARD HAS HIS PET "
    DUP BEAST W@ CO .W
    CR
    10 * +
;

: DISPACT ( -- ) ( DISPLAY SOME OF POTENTIAL ACTIONS )
    ." DO YOU WISH TO-" CR
    ." FIGHT, RUN, BRIBE?  " CR
;    


( SCREEN 32 )
: CHECKTREAS ( TREAS FLAG -- FLAG )
    DUP IF 
	SWAP TREASV C@ GEMS @ + DUP GEMS !
	." YOUR ILLGOTTEN GAINS NOW COME TO"
	# CO .W ."  POINTS"
    ELSE
	SWAP DROP
    THEN

;

: HASDIED ( -- )
    ." TOO BAD...THE MONSTER ATE YOU..." CR
    ." AND TOOK ALL YOUR TREASURE..." CR
    PRINCESS HAS IF
	." HE ALSO GOBBLED UP THE PRINCESS" CR
    THEN
;


( GOT THIS FAR )


( SCREEN 12 )



( SCREEN 13 )

( SCREEN 16 )


( SCREEN 17 )




( SCREEN 20 )

( SCREEN 21 )

( SCREEN 22 )

6 7 ARRAYST ACTCMD
" FIGHT" 0 ACTCMD W!
" RUN" 1 ACTCMD W!
" BRIBE" 2 ACTCMD W!
" ZAP" 3 ACTCMD W!
" ***" 4 ACTCMD W!
" BAT" 5 ACTCMD W!
" 0UT" 6 ACTCMD W!

: GETACT ( -- ACTION )
    S@
    -1 SWAP 7 0 DO
	I ACTCMD S= IF
	    SWAP DROP I SWAP LEAVE
	THEN
    LOOP
    CDROP
;	

( SCREEN 23 )
: EAGLE ;


( SCREEN 24 )

( SCREEN 25 )    




( SCREEN 26 )


( SCREEN 27 )

: HANDLELOC ( X Y -- X Y FLAG )
    ( FLAG = 1, IF SUCCESS; 0, PLAYER DIED )
    1 CHOICE ! ( INITIALLY, PLAYER HAS CHOICES )
    0 WIN !
    DISPSTRENGTH ( DISPLAY COMBAT STRENGTH )
    PICKMONSTER
    ( X Y MONSTER )
    7 RND ( PICK TREASURE, NOT PRINCESS )

    ( S : X Y MONST TREAS )
    DESCMON ( CREATE DESCRIPTION )

    ( X Y MONSTER TREASURE )
    OVER 10 * ( X Y MONSTER TREASURE MSTRENGTH )

    DUP 0= IF ( DEAL WITH MOUSE )
	." YOU GET THE TREASURE FOR FREE" CR
	1 ( AUTOMATICALLY SUCCEEDED )
    ELSE
	3 PICK 10 = IF 	( CHECK IF WIZARD HAS PET )
	    ADDPET
	THEN

	2 ( FLAG )
	( FIGHT, BRIBE, RUN )
	BEGIN
	    DROP
	    CHOICE @ IF
		DISPACT
		BEGIN
		    GETACT
		1+ ?DUP UNTIL 1- ( CHECK IF VALID INPUT )
	
		( S: X Y MONSTER TREASURE MSTRENGTH )
		CASE DOFIGHT DORUN DOBRIBE ZAP *** BAT OUT ;
	    ELSE
		DOFIGHT
	    THEN
	DUP 2 < UNTIL
    THEN

    SWAP DROP 
    CHECKTREAS
    SWAP DROP
;

( SCREEN 28 )

: MAINLOOP
    INITMAP
    INITPRINCESS
    INITPLAYER
    PRMAP
    PRCMPSS
    CLRSTAT
    
    BEGIN
	BEGIN
	    ?MOVE
	    MVP
	    DUP 0= IF
		NOENTRY
	    THEN
	UNTIL

	PRMAP
	HANDLELOC

	PRINCESS CHECKSTAT OVER AND
	IF FINDPRINCESS PRINCESS RESSTAT THEN
	PRCMPSS 100 PAUSE
    0= UNTIL
;

( GOT THIS FAR )


: ENCOUNTER ( X Y -- X Y FLAG )
    15 RND     ( CHOOSE MONSTER )

    ( CHECK IF PRINCESS )
    3 PICK 3 PICK MAP C@ 4 = IF
	DROP 10 THEN ( PRINCESS => WIZARD )

    ( CHECK FOR SPECIAL CASES )
    BEGIN
	1 OVER 10 > IF
	    OVER 11 -
	    CASE THIEF PIT BATTED EAGLE 1 -
	THEN
    UNTIL

    ( Check for eagle )
    DUP 2 = IF ( DEAL WITH EAGLE ) THEN

    ( DESCRIBE MONSTER )
    DESCMON ( BEAST -- BEAST )
    
    ( WORK OUT MONSTER'S STRENGTH )
    DUP 10 *
    
      Thief (11)
      Pit (12)
      Bat (13)
      Eagle (14 and S>4) - Exit
    Work out adjectives and print opponent info
    Check for dagger and 9
    Work out treasure
    Check if wizard has a ring
    Fight, bribe, or run
      If fight
        Check have enough strength
	Deduct from strength reserve
	Adjust for gold carried.
	H = 1000, 950, 900, ..., 0
	If L*M <= K and H>=I, Done
	Else repeat
)

( PRINT SPLASH SCREEN )
: SPLASHSCR ( -- )
;

( PRINT INSTRUCTIONS )
: INSTSCR ( -- )
;

    
: SWAMP ( -- )
    0 RAND ( RANDOMIZE GAME )
    SPLASHSCR
    INSTSCR

    ( GAME LOOP )
    BEGIN
	INITPLYR
	INITMAP

	PRINTMAP
	PRINTCMPSS

	BEGIN
	    ( GET DIRN )
	    ( CHECK FOR QUIT )
	    ( CHECK FOR MAP )
	    ( PROCESS DIRN )
	    ( CHECK FOR EXIT )
	    ( CHECK FOR SWAMP )
	WHILE
		( PLAY LOCATION )
		ENCOUNTER
		( ... )
	REPEAT
    UNTIL
;
    

( NOTES )

5 2 ARRAYST STRINGS
" HELLO" 0 STRINGS W!
" BYE" 1 STRINGS W!
1 STRINGS W@ CO .W!

